// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	CreateSubscriptionUser(ctx context.Context, arg CreateSubscriptionUserParams) (User, error)
	CreateUserPackage(ctx context.Context, arg CreateUserPackageParams) (UsersPackage, error)
	DeletePackage(ctx context.Context, id int64) error
	DeleteSubscriptionUser(ctx context.Context, id int64) error
	DeleteUserPackage(ctx context.Context, id int64) error
	GetPackages(ctx context.Context) ([]Package, error)
	GetSubscriptionUsers(ctx context.Context) ([]User, error)
	GetUserPackages(ctx context.Context) ([]GetUserPackagesRow, error)
	UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error)
	UpdateSubscriptionUser(ctx context.Context, arg UpdateSubscriptionUserParams) (User, error)
	UpdateUserPackage(ctx context.Context, arg UpdateUserPackageParams) (UsersPackage, error)
}

var _ Querier = (*Queries)(nil)
