// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPackage(ctx context.Context, arg CreateUserPackageParams) (UsersPackage, error)
	DeletePackage(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserPackage(ctx context.Context, id int64) error
	GetPackages(ctx context.Context) ([]Package, error)
	GetUserPackages(ctx context.Context) ([]GetUserPackagesRow, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPackage(ctx context.Context, arg UpdateUserPackageParams) (UsersPackage, error)
}

var _ Querier = (*Queries)(nil)
