apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: subscriptions-postgres
  template:
    metadata:
      labels:
        component: subscriptions-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DATABASE
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: subscriptions-postgres-service

---

apiVersion: v1
kind: Service
metadata:
  name: subscriptions-postgres-service
spec:
  type: ClusterIP
  selector:
    component: subscriptions-postgres
  ports:
    - port: 5432
      targetPort: 5432